### PR TITLE
Topic 2 Finished

### PR DESCRIPTION
**Pull request by F-Fischer**
Modular structure added and code-review comments fixed

### CODE REVIEW

**Comment by F-Fischer** [comment]
I have problems trying to split changes from another topic to make a clean PR. Next week, if you have time I want to ask some questions about it.

**Comment by marcelososa** [comment]
Ok Fran, you can do these steps:
First of all, I share you a tip to view a better git log:
```sh
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
```
Now you will see a better git log 👍 .

Going back to the changes:
```sh
# get the latest changes from origin
git fetch origin
# moving to the right branch
git checkout Topic-2
# checking the commit history in summary mode
git lg
# you will see somethig like that:
* 7c487ae - (HEAD -> fran-topic-2, fran/Topic-2) Topic 2 Finished (4 days ago) <F-Fischer>
* 34e0df6 - (fran/master, fran/Topic2) Topic 2 Finished (4 days ago) <F-Fischer>
* 053875f - Topic 2 up to exercise 8 (11 days ago) <F-Fischer>
* b993d01 - Topic 1 (2 weeks ago) <F-Fischer>
* c1e8a3f - (fran/Topic1) Topic 1 up to excercise 11 (3 weeks ago) <F-Fischer>
* 6c888a6 - Topic 1 up to Exercise 6 (3 weeks ago) <F-Fischer>
* 8e11f55 - Suggested changes added (3 weeks ago) <F-Fischer>
* c19eb88 - using html video tag instead of iframe (3 weeks ago) <F-Fischer>
* 8a67670 - Basic page structure using HTML CSS added (4 weeks ago) <F-Fischer>
* 3075220 - Sign Up Page v1 (4 weeks ago) <F-Fischer>
* 71fd915 - Multimedia Page Added (4 weeks ago) <F-Fischer>
* 8c1a969 - My todo List (4 weeks ago) <F-Fischer>
* 341ae26 - Primer commit, hello world! (4 weeks ago) <F-Fischer>
* 4ef986f - Added basic structure (4 weeks ago) <Ale Paciotti>
* 0527685 - Update README.md (4 weeks ago) <Alejandro Paciotti Iacchelli>
* c9b5a54 - Initial commit (4 weeks ago) <Alejandro Paciotti Iacchelli>
# now we need back to the begining, we go to the commit "4ef986f"
git checkout 4ef986f 
# checking if all right
git lg
* 4ef986f - (HEAD) Added basic structure (4 weeks ago) <Ale Paciotti>
* 0527685 - Update README.md (4 weeks ago) <Alejandro Paciotti Iacchelli>
* c9b5a54 - Initial commit (4 weeks ago) <Alejandro Paciotti Iacchelli>
# that's ok, now at this point we will create a new branch to move the right commits
git checkout -b Topic-2b
# now, we need apply all commits related to Topic 2, we can use the "cherry-pick" command
git cherry-pick b993d01
git cherry-pick 34e0df6
git cherry-pick 7c487ae
# ok, now check by git lg
git lg
* 44ec653 - (HEAD -> facu-topic-2b) Topic 2 Finished (8 seconds ago) <F-Fischer>
* 0713745 - Topic 2 Finished (68 seconds ago) <F-Fischer>
* 40f2d3e - Topic 2 up to exercise 8 (2 minutes ago) <F-Fischer>
* 4ef986f - Added basic structure (4 weeks ago) <Ale Paciotti>
* 0527685 - Update README.md (4 weeks ago) <Alejandro Paciotti Iacchelli>
* c9b5a54 - Initial commit (4 weeks ago) <Alejandro Paciotti Iacchelli>
# that's all! you are ready to update the PR
# but a few things before, we need to add a .gitignore file to avoid upload the node_modules folder
echo "/node_modules/" > francisco/.gitignore
# finally we need delete the node_module contents
git rm -r francisco/02-oop-inheritance/node_modules/
# add changes to create the commit
git add .
# and create a new commit
git commit -m "Topic 2 cleaned"
# only left update the PR (forced push)
git push -f personal Topic-2b:Topic-2
```

**Comment by F-Fischer** [comment]
Marcelo, first of all thanks for the help. Everything went okay, except the last step. When I tried this:

`git push -f personal Topic-2b:Topic-2`

I have this problem

`fatal: 'personal' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

I have tried with other git commands to make a force push, but without success.
It's okay if a try to make a pull request from another branch? From the Topic-2b, for example.
I made the same for a new branch for the topic 3 and it worked, but this topic is a new one and I don't have previous changes.

**Comment by marcelososa** [comment]
LGTM 👍

**Pull request merged**
